/* Shared practice companion. Tracks personal goals, never in-game scores. */
(()=>{'use strict';const script=document.currentScript,id=script.dataset.activity,title=script.dataset.title||'Practice',goals=JSON.parse(script.dataset.goals||'[]');if(!id||document.getElementById('kh-practice'))return;
const key='kidHubPractice:'+id;let state={done:[false,false,false],note:'',sessions:[]},started=0;
try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s&&Array.isArray(s.done)&&Array.isArray(s.sessions)){state.done=s.done.slice(0,3).map(Boolean);state.note=typeof s.note==='string'?s.note.slice(0,1000):'';state.sessions=s.sessions.filter(x=>x&&Number.isFinite(x.seconds)&&typeof x.date==='string').slice(-20)}}catch(e){}
const style=document.createElement('style');style.textContent='#kh-practice-toggle{position:fixed;bottom:12px;left:12px;z-index:2147483645;border:2px solid #fff;background:#36265f;color:white;border-radius:20px;padding:10px 16px;font:700 14px system-ui;cursor:pointer;min-height:44px}#kh-practice{position:fixed;inset:auto 12px 65px auto;z-index:2147483646;width:min(420px,calc(100vw - 24px));max-height:75vh;overflow:auto;box-sizing:border-box;background:#fff8ed;color:#25304a;border:3px solid #8a6ee7;border-radius:20px;padding:18px;font:16px/1.5 system-ui;box-shadow:0 8px 40px #0008;text-align:left}#kh-practice[hidden]{display:none}#kh-practice button,#kh-practice textarea{font:inherit;min-height:44px;border-radius:10px;padding:8px;border:1px solid #bbb;background:#fff;color:#25304a;max-width:100%;box-sizing:border-box}#kh-practice textarea{width:100%}#kh-practice label{display:block;margin:10px 0}#kh-practice input{width:20px;height:20px}#kh-practice h2{font:800 22px system-ui;color:#25304a;margin:8px 0}#kh-practice p{margin:10px 0}#kh-practice button{cursor:pointer;margin:4px}#kh-practice :focus-visible,#kh-practice-toggle:focus-visible{outline:3px solid #7953c5;outline-offset:3px}';document.head.append(style);
const toggle=document.createElement('button');toggle.id='kh-practice-toggle';toggle.type='button';toggle.textContent='🧭 Practice';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls','kh-practice');
const panel=document.createElement('section');panel.id='kh-practice';panel.hidden=true;panel.setAttribute('aria-label',title+' practice companion');panel.innerHTML='<button type="button" data-close aria-label="Close practice companion">✕ Close</button><h2></h2><p>Use the activity’s own pause control before opening this panel. This companion does not pause gameplay.</p><div data-goals></div><p data-progress></p><label>My strategy or discovery<textarea maxlength="1000" rows="3"></textarea></label><button type="button" data-start>Start practice timer</button><button type="button" data-finish disabled>Finish session</button><button type="button" data-export>↓ Export practice log</button><p data-status role="status"></p><p data-history></p><small>Goals and notes are self-reported, saved on this browser, and do not change game scores.</small>';document.body.append(toggle,panel);const $=s=>panel.querySelector(s);$('h2').textContent='🧭 '+title;
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('[data-status]').textContent='Practice saved on this device.'}catch(e){$('[data-status]').textContent='Storage unavailable; export your log to keep it.'}}
function render(){$('[data-progress]').textContent=state.done.filter(Boolean).length+'/3 personal goals explored';$('[data-history]').textContent=state.sessions.length+' saved sessions'+(state.sessions.length?' · Last session: '+state.sessions.at(-1).seconds+' seconds':'')}
goals.forEach((g,i)=>{const label=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.checked=!!state.done[i];c.onchange=()=>{state.done[i]=c.checked;save();render()};label.append(c,document.createTextNode(' '+g));$('[data-goals]').append(label)});$('textarea').value=state.note;$('textarea').oninput=e=>{state.note=e.target.value;save()};
toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden)$('[data-close]').focus()};$('[data-close]').onclick=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');toggle.focus()};
panel.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape')$('[data-close]').click()});panel.addEventListener('pointerdown',e=>e.stopPropagation());
$('[data-start]').onclick=()=>{started=Date.now();$('[data-start]').disabled=true;$('[data-finish]').disabled=false;$('[data-status]').textContent='Practice timer running. Close the panel and return when ready.'};
$('[data-finish]').onclick=()=>{if(!started)return;state.sessions.push({date:new Date().toISOString(),seconds:Math.round((Date.now()-started)/1000)});state.sessions=state.sessions.slice(-20);started=0;$('[data-start]').disabled=false;$('[data-finish]').disabled=true;save();render()};
$('[data-export]').onclick=()=>{const content=JSON.stringify({activity:title,goals,progress:state},null,2),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=id+'-practice.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};render();
})();
